### ISSUE TITLE
use of !!

### ISSUE THREAD

**Issue by hansen-simon** [digital-h-gmbh/devtools#14]
should we use always `!!`? 

There are scenarios, where a boolean value is needed and `undefined` breaks the application.
For example in react, when you have a check like: 
```
const someObj = {foo: {}};
return (
<>
  {someObj && someObj.foo && someObj.foo.bar && (
  <h1>nope</h1>
 )}
</>
```
This would fail, because the check would return `undefined` and `undefined` cannot be rendered in JSX.
Or when we write an object to firestore, the property need to be a boolean, undefined is not a valid value for firestore. 

In other scenarios `undefined` just gets evaluated as `false` like in if-statement or `*ngIf=".."`. 

We can distinguish these scenarios if this part of the source code can handle `undefined` and use `!!` only there, or use `!!` everywhere, because it does not hurt. Better safe than sorry :P 

On the other hand we would like to have clean code and remove clutter. 

What do you think?

**Comment by dennisschoepf** [comment]
You mean like this?: 

```
{!!(someObj && ...) && (
  <h1>Text</h1>
)}
```

I've set up a [Code Sandbox](https://codesandbox.io/embed/boring-monad-qvy37?fontsize=14&hidenavigation=1&theme=dark) for your example. As far as I can see it is valid React code and undefined is a falsy value which leads to the headline not rendering. It seems like that is what we want in this case, as you've written as well.

For other examples, where this leads to unexpected results, the question is if Typescript already handles the case (= enforces a boolean value). If it does, we should not need to enforce `!!` as it is up to the developer to deliver the correct data type.

Can you think of a case where Typescript would not handle such code issues and we would need to enforce it in another way?

**Comment by SimonSchoetz** [comment]
If there are unexpected errors, like you mentioned with firestore, Simon, I think it's a good idea to enforce a boolean instead of trusting falsy values are treated as we'd expect it. A solid approach imo would be to declare variables for these `someObj && someObj.foo && someObj.foo.bar`, like:
`const hasFooBar = !!someObj && someObj.foo && someObj.foo.bar;` (not sure if it'd need braces here)
`{hasFooBar && (<h1>... 
)}`
